### ISSUE TITLE
 no wasmer_jni in java.library.path  on MacOS

### ISSUE THREAD

**Issue by yuer1727** [wasmerio/wasmer-java#61]
### Summary

I try to run a wasm jni program in InteliJ  on  macOS ,  but I didn't make a success .  

### Additional details

Exception in thread "main" java.lang.UnsatisfiedLinkError: no wasmer_jni in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.wasmer.Instance.<clinit>(Instance.java:17)
	at Main.main(Main.java:18)

**Comment by Hywan** [comment]
Hello,

What's your CPU? How did you install `wasmer-java`? Thanks :-).

**Comment by johnkbarrow** [comment]
Hi - try adding "-Dos.arch=amd64" to your VM args
