### ISSUE TITLE
thread '<unnamed>' panicked at 'assertion failed: res.eax == 0'

### ISSUE THREAD

**Issue by cnyyl** [wasmerio/wasmer-java#70]
I found a runtime error as follow:

```
thread '<unnamed>' panicked at 'assertion failed: res.eax == 0', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/raw-cpuid-7.0.4/src/lib.rs:295:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Exception in thread "main" java.lang.RuntimeException: Any
    at org.wasmer.Instance.nativeInstantiate(Native Method)
    at org.wasmer.Instance.<init>(Instance.java:45)
```

I found this problem both on Windows 11 and Ubuntu 18.04, the JDK version is 1.8, is there anyone can help me to solve this problem?

**Comment by vikinatora** [comment]
I'm having the same issue on MacOS with Java 17.

**Comment by bengesoff** [comment]
Looks like it's possibly related to this, which was fixed in July 2021: https://github.com/gz/rust-cpuid/issues/45. However, wasmer-java's most recent release predates this fix.

From what I can see, this library used to be used by the wasmer project in 1.0.0, which is what wasmer-java depends on. However wasmer is now at version 3.1.1 and the cpuid library is no longer used.

**Comment by Tridu33** [comment]
this happens in windows 10
```cmd
Connected to the target VM, address: '127.0.0.1:6248', transport: 'socket'
thread '<unnamed>' panicked at 'assertion failed: res.eax == 0', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\raw-cpuid-7.0.4\src\lib.rs:295:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

java.lang.RuntimeException: Any

	at org.wasmer.Instance.nativeInstantiate(Native Method)
	at org.wasmer.Instance.<init>(Instance.java:45)
	at org.mvnsearch.WasmTest.testSimpleWasmCall(WasmTest.java:20)
```
